import { Inter } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";

import "./globals.css";
import PreHeader from "@/components/PreHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JOB PORTAL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PreHeader />

        {children}
      </body>
    </html>
  );
}
